cluster_name: {{cfg.name}}
num_tokens: {{cfg.tokens.num}}
allocate_tokens_for_keyspace: {{ cfg.tokens.allocate_for_keyspace}}
{{~#if cfg.tokens.initial }}
initial_token: {{ cfg.tokens.initial }}
{{~/if}}
hinted_handoff_enabled: {{cfg.hints.handoff_enabled}}
{{~#if cfg.hints.handoff_disabled_datacenters}}
hinted_handoff_disabled_datacenters:
  {{~#each cfg.hints.handoff_disabled_datacenters}}
  - {{this}}
  {{~/each~}}
{{~/if}}
max_hint_window_in_ms: {{cfg.hints.max_window_in_ms}}
hinted_handoff_throttle_in_kb: {{cfg.hints.handoff_throttle_in_kb}}
max_hints_delivery_threads: {{cfg.hints.max_delivery_threads}}
hints_directory: {{pkg.svc_var_path}}/hints
hints_flush_period_in_ms: {{cfg.hints.flush_period_in_ms}}
max_hints_file_size_in_mb: {{cfg.hints.max_file_size_in_mb}}
# {{~#if cfg.hints.compression}}
# hints_compression:
#   {{~#each cfg.hints.compression}}
#   - class_name: {{class_name}}
#   {{~#if parameters}}
#     parameters:
#     {{~#each parameters}}
#       - {{this}}
#     {{~/each~}}
#   {{~/if}}
#   {{~/each~}}
# {{~/if}}

batchlog_replay_throttle_in_kb: {{cfg.batchlog_replay_throttle_in_kb}}
authenticator: {{cfg.authentication.authenticator}}
authorizer: {{cfg.authentication.authorizer}}
role_manager: {{cfg.roles.manager}}
roles_validity_in_ms: {{cfg.roles.validity_in_ms}}
{{~#if cfg.roles.update_interval_in_ms}}
roles_update_interval_in_ms: {{cfg.roles.update_interval_in_ms}}
{{~/if}}
permissions_validity_in_ms: {{cfg.permissions.validity_in_ms}}
{{~#if cfg.permissions.update_interval_in_ms}}
permissions_update_interval_in_ms: {{cfg.permissions.update_interval_in_ms}}
{{~/if}}
credentials_validity_in_ms: {{cfg.credentials.validity_in_ms}}
{{~#if cfg.credentials.update_interval_in_ms}}
credentials_update_interval_in_ms: {{cfg.credentials.update_interval_in_ms}}
{{~/if}}

partitioner: {{ cfg.partitioner}}
data_file_directories:
    - {{pkg.svc_data_path}}
commitlog_directory: {{pkg.svc_var_path}}/commitlog
cdc_enabled: {{cfg.cdc.enabled}}
{{~#if cfg.cdc.enabled}}
{{pkg.svc_var_path}}/cdc_raw
{{~/if}}
disk_failure_policy: {{cfg.policy.disk_failure}}
commit_failure_policy: {{cfg.policy.commit_failure}}
prepared_statements_cache_size_mb: {{cfg.cache.prepared_statements.size_mb}}
thrift_prepared_statements_cache_size_mb: {{cfg.cache.prepared_statements.thrift_size_mb}}
key_cache_size_in_mb: {{cfg.cache.key.size_mb}}
key_cache_save_period: {{cfg.cache.key.save_period}}
{{~#if cfg.cache.key.key_to_save}}
key_cache_keys_to_save: {{cfg.cache.key.key_to_save}}
{{~/if}}
{{~#if cfg.cache.row.class_name}}
row_cache_class_name: {{cfg.cache.row.class_name}}
{{~/if}}
row_cache_size_in_mb: {{cfg.cache.row.size_in_mb}}
row_cache_save_period: {{cfg.cache.row.save_period}}
{{~#if cfg.cache.row.keys_to_save}}
row_cache_keys_to_save: {{cfg.cache.row.keys_to_save}}
{{~/if}}
counter_cache_size_in_mb: {{cfg.cache.counter.size_in_mb}}
counter_cache_save_period: {{cfg.cache.counter.save_period}}
{{~#if cfg.cache.counter.keys_to_save}}
counter_cache_keys_to_save: {{cfg.cache.counter.keys_to_save}}
{{~/if}}
saved_caches_directory: {{pkg.svc_var_path}}/saved_caches


{{~#if cfg.commitlog.sync.period_in_ms}}
commitlog_sync: periodic
commitlog_sync_period_in_ms: {{cfg.commitlog.sync.period_in_ms}}
{{ else }}
commitlog_sync: batch
commitlog_sync_batch_window_in_ms: {{cfg.commitlog.sync.batch_window_in_ms}}
{{~/if }}
commitlog_segment_size_in_mb: {{cfg.commitlog.segment_size_in_mb}}
# {{~#if cfg.commitlog.compression}}
# commitlog_compression:
#   {{~#each cfg.commitlog.compression}}
#   - class_name: {{class_name}}
#   {{~#if parameters}}
#     parameters:
#     {{~#each parameters}}
#       - {{this}}
#     {{~/each~}}
#   {{~/if}}
#   {{~/each~}}
# {{~/if}}
# seed_provider:
# {{~#if cfg.seed_provider }}
#   {{~#each cfg.seed_provider}}
#   - class_name: {{class_name}}
#   {{~#if parameters}}
#     parameters:
#     {{~#each parameters}}
#       - {{@key}}: {{this}}
#     {{~/each~}}
#   {{~/if}}
#   {{~/each~}}
# {{else}}
#     - class_name: org.apache.cassandra.locator.SimpleSeedProvider
#       parameters:
#           - seeds: "{{#each bind.cassandra.members}}{{#if @index}},{{/if}}{{sys.ip}}{{~/each}}"
# {{~/if}}
concurrent_reads: {{cfg.concurrent.reads}}
concurrent_writes: {{cfg.concurrent.writes}}
concurrent_counter_writes: {{cfg.concurrent.counter_writes}}
concurrent_materialized_view_writes: {{cfg.concurrent.materialized_view_writes}}
{{~#if cfg.cache.file.size_in_mb}}
file_cache_size_in_mb: {{cfg.cache.file.size_in_mb}}
{{~/if}}
{{~#if cfg.buffer_pool_use_heap_if_exhausted}}
buffer_pool_use_heap_if_exhausted: {{cfg.buffer_pool_use_heap_if_exhausted}}
{{~/if}}
{{~#if cfg.disk_optimization_strategy}}
disk_optimization_strategy: {{cfg.disk_optimization_strategy}}
{{~/if}}
{{~#if cfg.memtable.heap_space_in_mb}}
memtable_heap_space_in_mb: {{cfg.memtable.heap_space_in_mb}}
{{~/if}}
{{~#if cfg.memtable.offheap_space_in_mb}}
memtable_offheap_space_in_mb: {{cfg.memtable.offheap_space_in_mb}}
{{~/if}}
{{~#if cfg.memtable.cleanup_threshold}}
memtable_cleanup_threshold: {{cfg.memtable.cleanup_threshold}}
{{~/if}}
memtable_allocation_type: {{cfg.memtable.allocation_type}}
{{~#if cfg.commitlog.total_space_in_mb}}
commitlog_total_space_in_mb: {{cfg.commitlog.total_space_in_mb}}
{{~/if}}
{{~#if cfg.memtable.flush_writers}}
memtable_flush_writers: {{cfg.memtable.flush_writers}}
{{~/if}}
{{~#if cfg.cdc.total_space_in_mb}}
cdc_total_space_in_mb: {{cfg.cdc.total_space_in_mb}}
{{~/if}}
{{~#if cfg.cdc.free_space_check_interval_ms}}
cdc_free_space_check_interval_ms: {{cfg.cdc.free_space_check_interval_ms}}
{{~/if}}
{{~#if cfg.index_summary.capacity_in_mb}}
index_summary_capacity_in_mb: {{cfg.index_summary.capacity_in_mb}}
{{~/if}}
index_summary_resize_interval_in_minutes: {{cfg.index_summary.resize_interval_in_minutes}}
trickle_fsync: {{cfg.trickle_fsync.enable}}
trickle_fsync_interval_in_kb: {{cfg.trickle_fsync.interval_in_kb}}
storage_port: {{cfg.storage_port}}
ssl_storage_port: {{cfg.ssl_storage_port}}
{{~#if cfg.listen_address}}
listen_address: {{cfg.listen_address}}
{{else}}
listen_address: {{sys.ip}}
{{~/if}}
{{~#if cfg.listen_interface}}
listen_interface: {{cfg.listen_interface}}
{{~/if}}
{{~#if cfg.listen_interface_prefer_ipv6}}
listen_interface_prefer_ipv6: {{cfg.listen_interface_prefer_ipv6}}
{{~/if}}
{{~#if cfg.broadcast_address}}
broadcast_address: {{cfg.broadcast_address}}
{{~/if}}
{{~#if cfg.listen_on_broadcast_address}}
listen_on_broadcast_address: {{cfg.listen_on_broadcast_address}}
{{~/if}}
{{~#if cfg.internode.authenticator}}
internode_authenticator: {{cfg.internode.authenticator}}
{{~/if}}
start_native_transport: {{cfg.native_transport.start}}
native_transport_port: {{cfg.native_transport.port}}
{{~#if cfg.native_transport.port_ssl}}
native_transport_port_ssl: {{cfg.native_transport.port_ssl}}
{{~/if}}
{{~#if cfg.native_transport.max_threads}}
native_transport_max_threads: {{cfg.native_transport.max_threads}}
{{~/if}}
{{~#if cfg.native_transport.max_frame_size_in_mb}}
native_transport_max_frame_size_in_mb: {{cfg.native_transport.max_frame_size_in_mb}}
{{~/if}}
{{~#if cfg.native_transport.max_concurrent_connections}}
native_transport_max_concurrent_connections: {{cfg.native_transport.max_concurrent_connections}}
{{~/if}}
{{~#if cfg.native_transport.max_concurrent_connections_per_ip}}
native_transport_max_concurrent_connections_per_ip: {{cfg.native_transport.max_concurrent_connections_per_ip}}
{{~/if}}
start_rpc: {{cfg.rpc.start}}
rpc_address: {{cfg.rpc.address}}
{{~#if cfg.rpc.interface}}
rpc_interface: {{cfg.rpc.interface}}
{{~/if}}
{{~#if cfg.rpc.interface_prefer_ipv6}}
rpc_interface_prefer_ipv6: {{cfg.rpc.interface_prefer_ipv6}}
{{~/if}}
rpc_port: {{cfg.rpc.port}}
{{~#if cfg.rpc.broadcast_address}}
rpc_broadcast_address: {{cfg.rpc.broadcast_address}}
{{~/if}}
rpc_keepalive: {{cfg.rpc.keepalive}}
rpc_server_type: {{cfg.rpc.server_type}}
{{~#if cfg.rpc.min_threads}}
rpc_min_threads: {{cfg.rpc.min_threads}}
{{~/if}}
{{~#if cfg.rpc.max_threads}}
rpc_max_threads: {{cfg.rpc.max_threads}}
{{~/if}}
{{~#if cfg.rpc.send_buff_size_in_bytes}}
rpc_send_buff_size_in_bytes: {{cfg.rpc.send_buff_size_in_bytes}}
{{~/if}}
{{~#if cfg.rpc.recv_buff_size_in_bytes}}
rpc_recv_buff_size_in_bytes: {{cfg.rpc.recv_buff_size_in_bytes}}
{{~/if}}
{{~#if cfg.internode.send_buff_size_in_bytes}}
internode_send_buff_size_in_bytes: {{cfg.internode.send_buff_size_in_bytes}}
{{~/if}}
{{~#if cfg.internode.recv_buff_size_in_bytes}}
internode_recv_buff_size_in_bytes: {{cfg.internode.recv_buff_size_in_bytes}}
{{~/if}}
thrift_framed_transport_size_in_mb: {{cfg.thrift_framed_transport_size_in_mb}}
incremental_backups: {{cfg.incremental_backups}}
snapshot_before_compaction: {{cfg.snapshot.before_compaction}}
auto_snapshot: {{cfg.snapshot.auto}}
column_index_size_in_kb: {{cfg.column_index.size_in_kb}}
column_index_cache_size_in_kb: {{cfg.column_index.cache_size_in_kb}}
{{~#if cfg.concurrent_compactors}}
concurrent_compactors: {{cfg.concurrent_compactors}}
{{~/if}}
compaction_throughput_mb_per_sec: {{cfg.compaction_throughput_mb_per_sec}}
sstable_preemptive_open_interval_in_mb: {{cfg.sstable_preemptive_open_interval_in_mb}}
{{~#if cfg.stream_throughput_outbound_megabits_per_sec}}
stream_throughput_outbound_megabits_per_sec: {{cfg.stream_throughput_outbound_megabits_per_sec}}
{{~/if}}
{{~#if cfg.inter_dc_stream_throughput_outbound_megabits_per_sec}}
inter_dc_stream_throughput_outbound_megabits_per_sec: {{cfg.inter_dc_stream_throughput_outbound_megabits_per_sec}}
{{~/if}}
read_request_timeout_in_ms: {{cfg.coordinator.read_request_timeout_in_ms}}
range_request_timeout_in_ms: {{cfg.coordinator.range_request_timeout_in_ms}}
write_request_timeout_in_ms: {{cfg.coordinator.write_request_timeout_in_ms}}
counter_write_request_timeout_in_ms: {{cfg.coordinator.counter_write_request_timeout_in_ms}}
cas_contention_timeout_in_ms: {{cfg.coordinator.cas_contention_timeout_in_ms}}
truncate_request_timeout_in_ms: {{cfg.coordinator.truncate_request_timeout_in_ms}}
request_timeout_in_ms: {{cfg.coordinator.request_timeout_in_ms}}
slow_query_log_timeout_in_ms: {{cfg.slow_query_log_timeout_in_ms}}
cross_node_timeout: {{cfg.cross_node_timeout}}
{{~#if cfg.streaming_keep_alive_period_in_secs}}
streaming_keep_alive_period_in_secs: {{cfg.streaming_keep_alive_period_in_secs}}
{{~/if}}

# phi value that must be reached for a host to be marked down.
# most users should never need to adjust this.
# phi_convict_threshold: 8
{{~#if cfg.phi_convict_threshold}}
phi_convict_threshold: {{cfg.phi_convict_threshold}}
{{~/if}}
endpoint_snitch: {{cfg.snitch.endpoint}}
dynamic_snitch_update_interval_in_ms: {{cfg.snitch.update_interval_in_ms}}
dynamic_snitch_reset_interval_in_ms: {{cfg.snitch.reset_interval_in_ms}}
dynamic_snitch_badness_threshold: {{cfg.snitch.badness_threshold}}
request_scheduler: {{cfg.request_scheduler.class}}
{{~#if cfg.request_scheduler.id}}
request_scheduler_id: {{cfg.request_scheduler.id}}
{{~/if}}
server_encryption_options:
    {{~#with cfg.encryption.server }}
    internode_encryption: {{internode_encryption}}
    keystore: {{#if keystore }}{{keystore}}{{else}}{{../pkg.svc_config_path}}/.keystore{{/if}}
    keystore_password: {{keystore_password}}
    truststore: {{#if truststore }}{{truststore}}{{else}}{{../pkg.svc_config_path}}/.truststore{{/if}}
    truststore_password: {{truststore_password}}
    {{~#if protocol}}
    protocol: {{protocol}}
    {{~/if}}
    {{~#if algorithm}}
    algorithm: {{algorithm}}
    {{~/if}}
    {{~#if store_type}}
    store_type: {{store_type}}
    {{~/if}}
    {{~#if cipher_suites}}
    cipher_suites: {{cipher_suites}}
    {{~/if}}
    {{~#if require_client_auth}}
    require_client_auth: {{require_client_auth}}
    {{~/if}}
    {{~#if require_endpoint_verification}}
    require_endpoint_verification: {{require_endpoint_verification}}
    {{~/if}}
    {{~/with}}
client_encryption_options:
    {{~#with cfg.encryption.client }}
    enabled: {{enabled}}
    optional: {{optional}}
    keystore: {{#if keystore }}{{keystore}}{{else}}{{../pkg.svc_config_path}}/.keystore{{/if}}
    keystore_password: {{keystore_password}}
    {{~#if require_client_auth}}
    require_client_auth: {{require_client_auth}}
    {{~/if}}
    truststore: {{#if truststore }}{{truststore}}{{else}}{{../pkg.svc_config_path}}/.truststore{{/if}}
    {{~#if truststore_password}}
    truststore_password: {{truststore_password}}
    {{~/if}}
    {{~#if protocol}}
    protocol: {{protocol}}
    {{~/if}}
    {{~#if algorithm}}
    algorithm: {{algorithm}}
    {{~/if}}
    {{~#if store_type}}
    store_type: {{store_type}}
    {{~/if}}
    {{~#if cipher_suites}}
    cipher_suites: {{cipher_suites}}
    {{~/if}}
    {{~/with}}
internode_compression: {{cfg.internode.compression}}
inter_dc_tcp_nodelay: {{cfg.inter_dc_tcp_nodelay}}

tracetype_query_ttl: {{cfg.tracetype.query_ttl}}
tracetype_repair_ttl: {{cfg.tracetype.repair_ttl}}
{{~#if cfg.gc_log_threshold_in_ms}}
gc_log_threshold_in_ms: {{cfg.gc_log_threshold_in_ms}}
{{~/if}}
enable_user_defined_functions: {{cfg.enable_user_defined_functions}}
enable_scripted_user_defined_functions: {{cfg.enable_scripted_user_defined_functions}}
windows_timer_interval: {{cfg.windows_timer_interval}}
{{~#with cfg.encryption.transparent_data}}
transparent_data_encryption_options:
    enabled: {{enabled}}
    chunk_length_kb: {{chunk_length_kb}}
    cipher: {{cipher}}
    key_alias: {{key_alias}}
    {{~#if iv_length}}
    iv_length: {{iv_length}}
    {{~/if}}
    # {{~#if key_provider}}
    # key_provider:
    #   {{~#each key_provider }}
    #   - class_name: {{class_name}}
    #     {{~#if parameters}}
    #     parameters:
    #       {{~#each parameters}}
    #       - keystore: {{#if keystore }}{{keystore}}{{else}}{{../pkg.svc_config_path}}/.keystore{{/if}}
    #         keystore_password: {{keystore_password}}
    #         store_type: {{store_type}}
    #         key_password: {{key_password}}
    #       {{~/each}}
    #     {{~/if}}
    #   {{~/each}}
    # {{~/if}}
{{~/with}}
{{~#with cfg.threshold}}
tombstone_warn_threshold: {{tombstone_warn}}
tombstone_failure_threshold: {{tombstone_failure}}
batch_size_warn_threshold_in_kb: {{batch_size_warn_in_kb}}
batch_size_fail_threshold_in_kb: {{batch_size_fail_in_kb}}
unlogged_batch_across_partitions_warn_threshold: {{unlogged_batch_across_partitions_warn}}
compaction_large_partition_warning_threshold_mb: {{compaction_large_partition_warning_mb}}
gc_warn_threshold_in_ms: {{gc_warn_in_ms}}
{{~/with}}
{{~#if cfg.max_value_size_in_mb}}
max_value_size_in_mb: {{cfg.max_value_size_in_mb}}
{{~/if}}
back_pressure_enabled: {{cfg.back_pressure.enabled}}
{{~#if cfg.back_pressure.strategies}}
# back_pressure_strategy:
#     {{~#each cfg.back_pressure.strategies }}
#     - class_name: {{class_name}}
#       {{~#if parameters}}
#       parameters:
#         {{~#each parameters}}
#         - high_ratio: {{high_ratio}}
#           factor: {{factor}}
#           flow: {{flow}}
#         {{~/each}}
#       {{~/if}}
#     {{~/each}}
# {{~/if}}
